# Generated by Django 5.2.7 on 2025-11-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_casestudy_enhancedpricingpackage_faq_platformbenefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_category',
            field=models.IntegerField(choices=[(1, 'Webflyer Style'), (2, 'Irregular Format')], default=1, help_text='Category 1: Webflyer (images+link), Category 2: Full details'),
        ),
        migrations.AlterField(
            model_name='adplacement',
            name='max_file_size_mb',
            field=models.IntegerField(default=3),
        ),
    ]
