# Generated by Django 5.2.7 on 2025-11-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0003_ad_ad_category_alter_adplacement_max_file_size_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=20)),
                ('category', models.CharField(choices=[('film', 'Film'), ('theater', 'Theater'), ('concert', 'Concert')], max_length=20)),
                ('title', models.CharField(help_text='Event name', max_length=200)),
                ('venue_name', models.CharField(help_text='Theater/venue name', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='For multi-day events', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description (max 500 chars)', max_length=500)),
                ('ticket_link', models.URLField(blank=True, help_text='Link to buy tickets', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('venue_type', models.CharField(choices=[('cinema', 'Cinema'), ('theater', 'Theater'), ('concert_hall', 'Concert Hall'), ('multi_purpose', 'Multi-Purpose')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='ad',
            name='ad_category',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.IntegerField(choices=[(1, 'Type 1 - Webflyer Style'), (2, 'Type 2 - Irregular Format')], default=1, help_text='Type 1: Webflyer (images+link), Type 2: Full details'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports & Fitness'), ('furniture', 'Home & Furniture'), ('clothing', 'Clothing & Fashion'), ('electronics', 'Electronics'), ('food', 'Food & Beverages'), ('beauty', 'Beauty & Health'), ('automotive', 'Automotive'), ('other', 'Other')], default='other', help_text='Product/service category for filtering', max_length=50),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category'], name='ads_categor_68994b_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'event_date'], name='events_status_4e8a13_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'city'], name='events_categor_84c09a_idx'),
        ),
    ]
